spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      # default-filters
      default-filters:
        - name: GlobalLoggingFilter
          args:
            baseMessage: "=== Global Logging Filter ==="
            preLogger: true
            postLogger: true

      # routes
      routes:
        # AUTH-API
        - id: auth-api
          uri: lb://AUTH-API
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtAuthorizationHeaderFilter

        # CHOKCHOK-API
        - id: chokchok-api
          uri: lb://CHOKCHOK-API
          predicates:
            - Path=/api/**
          filters:
            - name: JwtAuthorizationHeaderFilter
  # env
  config:
    import: optional:file:.env[.properties]

# Server
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/

# JWT
jwt:
  secret: ${JWT_SECRETS}
  whitelist:
    - /auth/login
    - /api/members